### ISSUE TITLE
Data isn't NYT, it's copyrighted to AP

### ISSUE THREAD

**Issue by dwillis** [Deleetdk/USA.county.data#3]
In other words, you can't use it.

**Comment by Deleetdk** [comment]
One cannot copyright data.

**Comment by dwillis** [comment]
Unfortunately, in this case, AP collects it and licenses it and sells it. So you are in violation of their terms of use.

**Comment by akphi** [comment]
@dwillis I thought that you cannot copyright factual data, can you? I know quoting from [stack exchange](https://law.stackexchange.com/questions/11359/can-you-copyright-data) is not the best idea but I have been searching around the internet and find similar answers around the matter. But to your point, I did read the [term](https://www.ap.org/terms-and-conditions/), so I don't quite get it since NYT uses their data without addressing these terms, and if now people scrape from NYT website, then will the terms of use from AP still applied?

**Comment by dwillis** [comment]
@blacksteed232 What AP licenses is the ability to get it in one place. NYT and others pay the AP for this service and can publish the data as a result. You didn't, I presume. Scraping from the NYT is not a legal use of the AP's service. You could, as AP does, collect the data from each source and publish that.
