### ISSUE TITLE
Stale data

### ISSUE THREAD

**Issue by iabw** [Deleetdk/USA.county.data#4]
First, thanks. This was the only plain dataset of this I could find, so I definitely appreciate you making it available.

But, when I sum the vote totals for the 2016 election, I'm getting
results.clintonh: 59838642
results.trumpd: 59624676

The NYT page you link in the README has the totals displayed as 65,844,610 and 62,979,636. I know that not all states were done when you published this, and California didn't actually finish counting until mid-December, so I imagine that's why these numbers are off (or maybe due to absentee or provisional ballots, I don't know). In any case, 5-10% of the total seems like a significant difference that should be corrected if possible.

If you built some scraping tool to easily collate the numbers from the NYT with the county data from the sources described in your [earlier paper](https://openpsych.net/files/papers/Kirkegaard_2016e.pdf), maybe you could share or re-run it? Or describe your method in a little more detail, so it could be replicated?

**Comment by Deleetdk** [comment]
The NYT makes the data available in a JSON that is downloaded by the browser in the background. Turn on the F12 menu (network tab) to see the background files.

The JSON files:

https://int.nyt.com/newsgraphics/2016/elections/primaries/topojson/usa/counties-general-albers-19p.json
https://intf.nyt.com/newsgraphics/2016/11-08-election-forecast/president.json

The data are, unfortunately, messy, so one has to do some cleaning, and then finally merge with the other county data. It also looks like they have changed the format since I did it last time, so my code doesn't work.

**Comment by iabw** [comment]
Thanks for the tips. If you're not planning to, and I follow through on re-compiling this, I'll submit a pull request.

**Comment by Deleetdk** [comment]
The 2016 data are no longer in the JSON files. It is now embedded inside the HTML file (line 25,388 as of now). You can see it in the source code.

http://www.nytimes.com/elections/results/president

Search for the name of a county with a distinctive name. I used "Glacier" because it's easy to find on the map (blue one in the top of Montana).

So, to get the updated data, copy the JSON object from the HTML, paste it into a new JSON file, then load that into R (or Python). I did that just now. The data are pretty messy. There is a list with 51 members, one for each state. Each member is a data.frame, with an embedded data.frame. So one has to unpack these and finally merge to one data.frame. Example:

```
> json_updated$counties[[2]] %>% str
'data.frame':	67 obs. of  7 variables:
 $ fips               : chr  "01107" "01007" "01079" "01115" ...
 $ name               : chr  "Pickens" "Bibb" "Lawrence" "St. Clair" ...
 $ votes              : int  9494 8748 14623 37937 13025 10948 42030 94090 18255 6931 ...
 $ reporting          : int  35 10 31 32 35 24 29 48 20 27 ...
 $ precincts          : int  35 10 31 32 35 24 29 48 20 27 ...
 $ est_votes_remaining: int  0 0 0 0 0 0 0 0 0 0 ...
 $ results            :'data.frame':	67 obs. of  4 variables:
  ..$ trumpd  : int  5454 6733 10732 31579 7681 5224 30567 72780 15068 5819 ...
  ..$ clintonh: int  3972 1874 3611 5550 5039 5607 10547 18409 2909 1035 ...
  ..$ johnsong: int  49 124 249 678 257 104 772 2448 226 62 ...
  ..$ steinj  : int  19 17 31 130 48 13 144 453 52 15 ...
```

I then turned on the flatten feature in jsonlite, and it correctly flattened the 51 data.frames, so that one can just merge them.

```
> json_updated$counties[[2]] %>% str
'data.frame':	67 obs. of  10 variables:
 $ fips               : chr  "01107" "01007" "01079" "01115" ...
 $ name               : chr  "Pickens" "Bibb" "Lawrence" "St. Clair" ...
 $ votes              : int  9494 8748 14623 37937 13025 10948 42030 94090 18255 6931 ...
 $ reporting          : int  35 10 31 32 35 24 29 48 20 27 ...
 $ precincts          : int  35 10 31 32 35 24 29 48 20 27 ...
 $ est_votes_remaining: int  0 0 0 0 0 0 0 0 0 0 ...
 $ results.trumpd     : int  5454 6733 10732 31579 7681 5224 30567 72780 15068 5819 ...
 $ results.clintonh   : int  3972 1874 3611 5550 5039 5607 10547 18409 2909 1035 ...
 $ results.johnsong   : int  49 124 249 678 257 104 772 2448 226 62 ...
 $ results.steinj     : int  19 17 31 130 48 13 144 453 52 15 ...
```

R code:

```
json_updated = jsonlite::fromJSON("data/updated.json", flatten = T)
d_this = dplyr::bind_rows(json_updated$counties) %>% as_data_frame
```

produces:

```
> d_this
# A tibble: 3,113 × 38
    fips      name  votes reporting precincts results.trumpd results.clintonh results.johnsong results.steinj
   <chr>     <chr>  <int>     <int>     <int>          <int>            <int>            <int>          <int>
1  02000    Alaska 246588       440       442         130415            93007            14593           4445
2  01107   Pickens   9494        35        35           5454             3972               49             19
3  01007      Bibb   8748        10        10           6733             1874              124             17
4  01079  Lawrence  14623        31        31          10732             3611              249             31
5  01115 St. Clair  37937        32        32          31579             5550              678            130
6  01109      Pike  13025        35        35           7681             5039              257             48
7  01091   Marengo  10948        24        24           5224             5607              104             13
8  01069   Houston  42030        29        29          30567            10547              772            144
9  01003   Baldwin  94090        48        48          72780            18409             2448            453
10 01021   Chilton  18255        20        20          15068             2909              226             52
# ... with 3,103 more rows, and 29 more variables: results.castled <int>, results.de_la_fuenter <int>,
#   est_votes_remaining <int>, results.mcmulline <int>, results.hedgesj <int>, results.kahnl <int>,
#   results.la_rivag <int>, results.hoeflingt <int>, results.kenistonc <int>, results.smithm <int>,
#   results.atwoodf <int>, results.kennedya <int>, results.kopitkek <int>, results.kotlikoffl <int>,
#   results.lyttleb <int>, results.maldonadoj <int>, results.maturenm <int>, results.scottr <int>,
#   results.silvar <int>, results.soltysike <int>, results.vacekd <int>, results.copelands <int>,
#   results.jacobp <int>, results.whitej <int>, results.mooreheadm <int>, results.none_of_these_candidates <int>,
#   results.duncanr <int>, results.skewesp <int>, results.giordanir <int>
```

Which can then be merged by the fips code. Beware that Alaska has no counties, so instead the state-level results are given.

**Comment by Deleetdk** [comment]
@iabw did you update the data?

It seems I didn't, or I didn't commit the change. Whatever the case, I will need these data for an upcoming project or two. And then I'll update to the final numbers. I did save the information.

**Comment by iabw** [comment]
No, I haven't.

**Comment by Deleetdk** [comment]
Updated data to final data https://github.com/Deleetdk/USA.county.data/commit/a794e9c68744404f251e66a1ccb268cf6752bfbc.
